name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        opensearch-version: [1]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.
      with:
        opensearch-version: ${{ matrix.opensearch-version }}
        plugins: |
          analysis-kuromoji
          analysis-smartcn
    - run: curl -s localhost:9200
    - run: which opensearch
    - run: opensearch-plugin list
