name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # fails on other platforms
        # see https://github.com/ankane/setup-opensearch/issues/1
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]
        opensearch-version: [1]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.
      with:
        opensearch-version: ${{ matrix.opensearch-version }}
        plugins: |
          analysis-kuromoji
          analysis-smartcn
    - run: curl -s localhost:9200
    - run: which opensearch
    - run: opensearch-plugin list
